
apiVersion: gateway.kyma-project.io/v1alpha2
kind: Api
metadata:
  name: personservice
  labels:
     app: personservice
spec:
  hostname: personservice
  service:
    name: personservice
    port: 8080
---
apiVersion: v1
kind: Service
metadata:
  labels:    
     app: personservice
     version: "0.0.3"
  annotations:
     auth.istio.io/80: NONE
  name: personservice
spec:
  ports:
  - name: http
    port: 8080
  selector:
    app: personservice
    version: "0.0.3"
  type: NodePort
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: personservice-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
   annotations:
      deployment.kubernetes.io/revision: "3"
   labels:
      app: personservice
      mf_version: "2"
   name: personservice   
spec:
   replicas: 1
   selector:
      matchLabels:
         app: personservice
   template:
      metadata:
         labels:    
            app: personservice
            version: "0.0.3"
         annotations:
            sidecar.istio.io/inject: "true"
      spec:    
         containers:
           - name: personservice
# changeme: Replace with pointer to your docker repository/container
             image: "arifcrtsap/mongokubernetes:0.0.3"
             resources:
                limits:
                   memory: 1Gi
             imagePullPolicy: Always              
             ports:
              - containerPort: 8080
                name: http
              - containerPort: 8081
                name: actuatorhttp
      
             env:
              - name: spring_data_mongodb_host
                valueFrom: 
                   configMapKeyRef:
                      name: mongo-kubernetes-config
                      key: mongodb_host 
              - name: spring_data_mongodb_database
                valueFrom: 
                   configMapKeyRef:
                      name: mongo-kubernetes-config
                      key: mongodb_database 
              - name: spring_data_mongodb_authentication_database
                valueFrom: 
                   configMapKeyRef:
                      name: mongo-kubernetes-config
                      key: authentication_database 
              - name: spring_data_mongodb_password
                valueFrom: 
                   secretKeyRef:
                      name: first-mongo-mongodb
                      key: mongodb-root-password 
              - name: spring_data_mongodb_username
                valueFrom: 
                   configMapKeyRef:
                      name: mongo-kubernetes-config
                      key: mongodb_username
              - name: personservicekubernetes_applicationconnetor_baseurl
                valueFrom: 
                   configMapKeyRef:
                      name: mongo-kubernetes-config
                      key: connector_baseurl
              - name: spring_profiles_active
                value: "ApplicationConnector" 
              - name: management_health_redis_enabled
                value: "false"                      
             volumeMounts:
              - mountPath: /jks
                name: jks-persistent
              - mountPath: /registration
                name: registrationfile
                readOnly: true
              - mountPath: /security
                name: kyma-certificate
                readOnly: true
         volumes:
          - name: jks-persistent
            persistentVolumeClaim:
               claimName: personservice-pvc
          - name: registrationfile
            configMap:
              name: registrationfile 
              items:
               - key: registrationfile.json
                 path: registrationfile.json
          - name: kyma-certificate
            secret:
              secretName: kyma-certificate
                                                          
