{
 "title": "Person Service Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Megabytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{namespace=\"personservice\",container=\"personservice\"}/1000000",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Number of Person Service Instances",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(up{job=\"personservice-actuator\"})",
     "legendFormat": "Number of Person Service Instances"
    }
   ]
  },
  {
   "title": "Person DB Size",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(personservice_persistency_repository_size{Repository=\"Persons\"})",
     "legendFormat": "Persons"
    }
   ]
  },
  {
   "title": "Requests per Minute",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "Requests / Minute" }
   ],
   "targets": [
    {
     "expr": " sum by (job,method) (rate(http_server_requests_seconds_count{job=\"personservice-actuator\"}[1m])*60)",
     "legendFormat": "{{method}}"
    }
   ]
  }
 ]
}